"""
feature_store/schema.py
────────────────────────
Pydantic schemas and metadata dataclasses for QuantSphereX Feature Store.
Enforces institutional schema definition, feature validation bounds, and version manifests.
"""

from __future__ import annotations
from datetime import datetime
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field, field_validator


class FeatureDefinition(BaseModel):
    """Schema definition for an individual feature column."""
    name: str = Field(..., description="Feature column name")
    dtype: str = Field("float64", description="Expected pandas numeric type")
    category: str = Field("General", description="Factor family category (e.g. Momentum, Volatility)")
    description: Optional[str] = Field(None, description="Detailed explanation of factor calculation")
    min_value: Optional[float] = Field(None, description="Expected minimum value threshold for sanity checks")
    max_value: Optional[float] = Field(None, description="Expected maximum value threshold for sanity checks")
    allow_null: bool = Field(True, description="Whether NaNs are allowed in feature data")
    max_null_pct: float = Field(0.20, description="Maximum allowed NaN fraction across panel")
    is_lagged: bool = Field(True, description="Asserts if factor is shifted (t-1) for zero look-ahead")


class FeatureSchema(BaseModel):
    """Container schema for a set of feature definitions."""
    schema_id: str = Field(..., description="Unique schema identifier (e.g. 'alpha_v5_schema')")
    version: str = Field(..., description="Semantic version string, e.g. '1.0.0'")
    features: Dict[str, FeatureDefinition] = Field(..., description="Map of feature_name -> FeatureDefinition")
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())

    @field_validator("version")
    @classmethod
    def validate_semver(cls, v: str) -> str:
        parts = v.split(".")
        if len(parts) < 2:
            raise ValueError("Version must be dot-separated semver, e.g., '1.0.0'")
        return v


class FeatureVersion(BaseModel):
    """Manifest describing a persisted feature dataset version."""
    version_id: str = Field(..., description="Unique version identifier string")
    schema_id: str = Field(..., description="Schema ID referenced by this feature version")
    start_date: str = Field(..., description="Start date of dataset panel (YYYY-MM-DD)")
    end_date: str = Field(..., description="End date of dataset panel (YYYY-MM-DD)")
    tickers_hash: str = Field(..., description="Hash of sorted tickers contained in dataset")
    data_hash: str = Field(..., description="Content hash (SHA-256) of feature matrix")
    row_count: int = Field(..., description="Total row count of MultiIndex panel")
    feature_count: int = Field(..., description="Number of feature columns stored")
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    lineage_id: Optional[str] = Field(None, description="ID of lineage transformation record")


class ValidationReport(BaseModel):
    """Report generated by FeatureStoreValidator audit."""
    is_valid: bool = Field(..., description="True if no severe schema violations occurred")
    total_rows: int = Field(..., description="Total rows audited")
    feature_errors: Dict[str, List[str]] = Field(default_factory=dict, description="Errors per feature column")
    warnings: List[str] = Field(default_factory=list, description="Non-fatal warnings recorded")
    checked_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
